### ISSUE TITLE
2008 R2 and 2012 Server

### ISSUE THREAD

**Issue by maddman1901** [arcadejust/MultiotpCPV2RDP#1]
Any way to get this to work with Windows 2008 R2 and 2012 Server editions?
Thanks

**Comment by arcadejust** [comment]
Sure thing, I will be adjusting my code to win 8.1 - and it should work alright then. Funny thing is that the difference between win 8.0 and win 8.1 is more drastic than between win 8.1 and win 10:P

**Comment by maddman1901** [comment]
Very cool. I tried to use current coded with 2008 R2 but I get a "LogonUI.exe - System Error" MSVCP140.dll is missing. Thanks for the help.

**Comment by arcadejust** [comment]
True, I had to use static linking - try now

**Comment by maddman1901** [comment]
It seems like the opposite of what should be happening is happening. I don't get the 2-Factor Auth at RDP but I get it at console login. The MultiOneTimePasswordCredentialProviderSetup-3.0.701.153 is setup to be the "Default Provider".

When MultiOneTimePasswordCredentialProviderSetup-3.0.701.153 is not setup as the "Default Provider", and I try to RDP, I get a "Cancel" button. 
![win2k8server](https://cloud.githubusercontent.com/assets/16217911/11697692/c63a6d24-9e88-11e5-9c32-13cafa63450d.jpg)

**Comment by arcadejust** [comment]
It was all but working I'm afraid - done some corrections and now it should work - use devel version (first rename it). This should work and if not give me a log file from C:\multiotplog.txt

Update 1:But wait, I think you are not referring to my credential provider, you should have provider with key {FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} right?

Update 2:I'm downloading Win Server 2012 R2 - I will run my dll and check it - are you using local or domain account?

**Comment by maddman1901** [comment]
Update 1: I uninstalled the MultiOneTimePasswordCredentialProviderSetup-3.0.701.153 and reran your reg file. I also renamed and copied the dev version to the windows\system32 folder. On RDP connection I only get the same "Cancel" button as before. System has been rebooted too.

Update 2: I am using local accounts.
Thank you for all the help

Log attached:
[multiotplog.txt](https://github.com/arcadejust/MultiotpCPV2RDP/files/57365/multiotplog.txt)

**Comment by maddman1901** [comment]
I tested in Windows 2012 R2 and it works great. Not sure why I keep getting the blank screen with the "Cancel" button in Windows 2008 R2.

**Comment by arcadejust** [comment]
I can see that your system is not providing the user list:

> 20151209 2133310817: Unassigned User List
> 20151209 2133310817: Unassigned UserArray

I will try and tinker with it a bit... when I download 2008 R2. Yesterday I have waited for the 2012 R2 to download and I fell a sleep:P So I'm happy to hear that it works in Windows server 2012 R2 and will get back to you when I test it on 2008.

Update: Microsoft no longer offers Windows Server 2008 R2 for trial - so I don't know how to test it...

**Comment by maddman1901** [comment]
Link to the 180 day test for Win2K8R2:
https://www.microsoft.com/en-us/download/details.aspx?id=11093

**Comment by maddman1901** [comment]
I found another issue for you but this one is with Windows 2012. Multiotp works great but when I try to browse another computer from the server, and the other machine doesn't have the same credentials, I get the attached picture.
![error](https://cloud.githubusercontent.com/assets/16217911/11754878/51a8e8ce-a01c-11e5-9dbb-4d02cba377ab.jpg)

As you can see it doesn't give me a place to put in a username and password to authenticate to another machine.

**Comment by arcadejust** [comment]
You know Win2K8R2 uses Credential Provider V1, not V2... So don't expect miracles:) I've made it work though.

Update: On this image you see a CredUI and it was set as implemented by mistake. So I have corrected this as we speak. You can try it now.

**Comment by maddman1901** [comment]
You are the MAN! Thank you very much it works great.

**Comment by arcadejust** [comment]
You are welcome:D

Update: I don't know how to close the issue:P
