### ISSUE TITLE
Collaboration with multiOTP dev team

### ISSUE THREAD

**Issue by multiOTP** [arcadejust/MultiotpCPV2RDP#2]
Hello Arcadejust,

Nice upgrade of LastSquirrel work, could you please contact us per email at info [at] multiotp.net to discuss about the features of our new release.

Best regards and happy New Year!

**Comment by arcadejust** [comment]
Sure thing, happy New Year to LastSquirrel team:)

**Comment by multiOTP** [comment]
Unfortunately, I think the LastSquirrel team is no more up, the website doesn't exists anymore!
